name: Weekly Contributions

on:
  schedule:
    - cron: '0 20 * * 0'  # runs at 20:00 every sunday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub matplotlib

    - name: Run the script
      run: python analyze_contributions.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
