name: Weekly Contributions

on:
  schedule:
    - cron: '0 20 * * 0'  # runs at 20:00 every Sunday
  workflow_dispatch: # allows manual triggering

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and Run Docker Compose
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          docker-compose build
          docker-compose up

      - name: Update README.md image link to cache-bust
        run: |
          # current value (defaults to 0 if the pattern isn’t found yet)
          CUR=$(grep -oE 'commit_distribution\.png\?beep-boop-[0-9]+' README.md \
                | grep -oE '[0-9]+' | head -1)
          CUR=${CUR:-0}
          NEXT=$((CUR + 1))

          # replace the old number with the incremented one
          sed -i -E "s/(commit_distribution\.png\?beep-boop-)[0-9]+/\1${NEXT}/" README.md

      - name: Configure Git
        run: |
          git config http.sslVerify false
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote add publisher "https://${{ github.actor }}:${{ secrets.TOKEN }}@github.com/${{ github.repository }}.git"
          git show-ref

      - name: Commit and Push Updated Data
        run: |
          git add *.png README.md
          git commit -m "Update commit distribution piechart $(date -u)" || exit 0
          git push publisher master
          echo "success"

      - name: Clean up
        run: docker-compose down
