name: Weekly Contributions

on:
  schedule:
    - cron: '0 20 * * 0'  # runs at 20:00 every sunday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t contributions-analyzer .

    - name: Run Docker Container
      run: docker run -e GITHUB_TOKEN=${{ secrets.TOKEN }} contributions-analyzer
