name: Weekly Contributions

on:
  schedule:
    - cron: '0 20 * * 0'  # runs at 20:00 every Sunday
  workflow_dispatch: # allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Run Docker Compose
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          docker-compose build
          docker-compose up

      - name: Correct File Ownership
        run: |
          sudo chown -R $(whoami) commit_distribution.png

      - name: Check token scopes
        run: |
          curl -H "Authorization: token ${{ secrets.TOKEN }}" https://api.github.com/rate_limit

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin https://${{ secrets.TOKEN }}@github.com/teodord25/teodord25.git

      - name: Commit and Push Updated Data
        run: |
          echo "--------------------"
          git status
          echo "--------------------"
          git add commit_distribution.png
          echo "--------------------"
          git status
          echo "--------------------"
          git commit -m "Update commit distribution piechart"
          git push origin master
          echo "--------------------"
          git log -1

      - name: Clean up
        run: docker-compose down
