name: Weekly Contributions

on:
  schedule:
    - cron: '0 20 * * 0'  # runs at 20:00 every Sunday
  workflow_dispatch: # allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Run Docker Compose
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          docker-compose build
          docker-compose up

      - name: Configure Git
        run: |
          git config http.sslVerify false
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote add publisher "https://${{ github.actor }}:${{ secrets.TOKEN }}@github.com/${{ github.repository }}.git"
          git show-ref

      - name: Commit and Push Updated Data
        run: |
          git add commit_distribution.png
          git commit -m "Update commit distribution piechart ${$(date -u)}" || exit 0
          git push publisher master

      - name: Clean up
        run: docker-compose down
